version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Volume para persistir as imagens (importante!)
      - ./public/images:/app/public/images:ro
    restart: unless-stopped
    
  # Nginx para servir arquivos estáticos (opcional, para produção)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public/images:/usr/share/nginx/html/images:ro
    depends_on:
      - frontend
    restart: unless-stopped
    profiles:
      - production